- name: secrets | load etcd ca
  run_once: true
  slurp:
    src: "/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt"
  register: slurped_etcd_ca_file

- name: secrets | load etcd cert
  run_once: true
  slurp:
    src: "/var/lib/rancher/k3s/server/tls/etcd/server-client.crt"
  register: slurped_etcd_cert_file

- name: secrets | load etcd cert key
  run_once: true
  slurp:
    src: "/var/lib/rancher/k3s/server/tls/etcd/server-client.key"
  register: slurped_etcd_cert_key_file
