- name: secrets | load etcd ca
  run_once: true
  slurp:
    src: "/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt"
  register: slurped_etcd_ca_file

- name: secrets | load etcd cert
  run_once: true
  slurp:
    src: "/var/lib/rancher/k3s/server/tls/etcd/server-client.crt"
  register: slurped_etcd_cert_file

- name: secrets | load etcd cert key
  run_once: true
  slurp:
    src: "/var/lib/rancher/k3s/server/tls/etcd/server-client.key"
  register: slurped_etcd_cert_key_file

- name: secrets | deploy coredns-etcd secret manifest
  run_once: true
  ansible.builtin.template:
    src: "coredns-etcd.yaml.j2"
    dest: "{{ k3s_server_manifests_dir }}/coredns-etcd.yaml"
    mode: 0600

- name: secrets | deploy sops secret manifest
  run_once: true
  ansible.builtin.template:
    src: "gpg-secret.yaml.j2"
    dest: "{{ k3s_server_manifests_dir }}/gpg-secret.yaml"
    mode: 0600
