apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: docker-registry
    namespace: registry
spec:
    interval: 5m
    chart:
        spec:
          # renovate: registryUrl=https://helm.twun.io
          chart: docker-registry
          version: 1.10.1
          sourceRef:
            kind: HelmRepository
            name: twuni-charts
            namespace: flux-system
    values:
        image:
            repository: registry
            tag: 2.7.1
            pullPolicy: IfNotPresent
        imagePullSecrets:
            - name: regcred
        ingress:
            enabled: true
            path: /
            # Used to create an Ingress record.
            hosts:
              - registry-mirror.${SECRET_DOMAIN}
            tls:
              - secretName: ""
                hosts:
                  - registry-mirror.${SECRET_DOMAIN}
        service:
          type: LoadBalancer
          loadBalancerIP: "${LB_REGISTRY_IP}"
        persistence:
          accessMode: ReadWriteOnce
          enabled: true
          size: 100Gi
          storageClass: "${SC_DEFAULT}"
        # set the type of filesystem to use: filesystem, s3
        storage: filesystem
        # Secrets for S3 access and secret keys
        #   s3:
        #     accessKey: ""
        #     secretKey: ""
        configData:
          version: 0.1
          log:
              fields:
                  service: registry
          storage:
              cache:
                  blobdescriptor: inmemory
          http:
              addr: :5000
              headers:
                  X-Content-Type-Options:
                      - nosniff
          # TODO securely add credentials
          proxy:
              remoteurl: https://registry-1.docker.io
