apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bitnami-charts.yaml
- ingress-nginx-charts.yaml
- jetstack-charts.yaml
- k8s-at-home-charts.yaml
- traefik-charts.yaml
- kubernetes-dashboard-charts.yaml
- dex-charts.yaml
- elastic-charts.yaml
- influxdata-charts.yaml
- loki-charts.yaml
- nextcloud-charts.yaml
- vernemq-charts.yaml
- prometheus-community-charts.yaml
