apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: docker-registry
    namespace: registry
spec:
    interval: 5m
    chart:
        spec:
          # renovate: registryUrl=https://helm.twun.io
          chart: docker-registry
          version: 1.10.1
          sourceRef:
            kind: HelmRepository
            name: twuni-charts
            namespace: flux-system
    values:
        image:
            repository: registry
            tag: 2.7.1
            pullPolicy: IfNotPresent
        imagePullSecrets:
            - name: regcred
        ingress:
            enabled: true
            path: /
            # Used to create an Ingress record.
            hosts:
              - registry-mirror.${SECRET_DOMAIN}
            tls:
              - secretName: ""
                hosts:
                  - registry-mirror.${SECRET_DOMAIN}
        persistence:
          accessMode: ReadWriteOnce
          enabled: false
          size: 10Gi
          # storageClass: '-'
        # set the type of filesystem to use: filesystem, s3
        storage: filesystem
        # Secrets for S3 access and secret keys
        #   s3:
        #     accessKey: ""
        #     secretKey: ""
        configData:
          version: 0.1
          log:
              fields:
                  service: registry
          storage:
              cache:
                  blobdescriptor: inmemory
          http:
              addr: :5000
              headers:
                  X-Content-Type-Options:
                      - nosniff
          # Encrypt credentials using: sops --encrypt --in-place --encrypted-regex 'password|username' cluster/core/registry/helm-release.yaml
          proxy:
              remoteurl: https://registry-1.docker.io
              username:
                  - ENC[AES256_GCM,data:5D8vufcEU0k=,iv:K47dJ92QyCXJK9AVmXRHgS6khKx8bm/L2unwWkX464Y=,tag:SFHNaDa6NzqLesONibFrbw==,type:str]
              password:
                  - ENC[AES256_GCM,data:SNa8h6ZD5o8=,iv:KlCNlmC2Na7rB2M+FgtZHBrS4AmLwbybHoaje1BjW2A=,tag:7+Q4xSFa9H49fmrtPAXCnw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-01T18:27:06Z"
    mac: ENC[AES256_GCM,data:McUaKkVyyBr0jE+k/rCyDPIEqEqUOkNUnPWbXAZMaNa0WPBrkIMw2/zIYcOSeAIgFVidcAJ3xLSzunsm7yvWOVz9jy2LxGvFa+wdYKhUe+yGBcQ38/pHDOILewdNdiJ2Kdb0aLZx8VdprRExTb673k7cNj95R8UIcJCNhM8e0BE=,iv:+lMuaDm4BFM2SyJ+VR94iZDseStF3Ffz534onQPTUro=,tag:Q93jWObh4qG8ieueQllL3g==,type:str]
    pgp:
        - created_at: "2021-05-01T18:27:06Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/auLpaX8YHdAQ//bGnDvDdlLzq6Mndfys/Eh1pVWmlG164V+gFBByvK9XTI
            b5lEbKpiQkzdLiKMFGTsF72Qxjk8oLsDJRGGrTwBAUPpnSEhuU10ASvNBIKfT2k0
            z3XxWfokTxcenRL9lf3EW+ts08jICrQk/TF96SnfuKSec+lsyja3dxyUqe7JrhWg
            bBmgt1nHqrq/Fto20XLoZIjHP3xxqa0TaFj5xAuKjT7pDhOlKktB8Ji7N9Der0Xw
            ujQBmmHpuXKqdUgrobVx4zaMSiuWJNw1sxv7LOIMD+cRFg7gx2tIw6UzC7IR/BEI
            TMYEItLgxKuNwT/mPLyIHUbvZ5rHSswxIvO5tmz9hRiW4F7AhCucaDXKMRQvvd06
            alSjmxrgHV/XwSAV0w2TC8XdDNfdWMFcrHXTlCsSgZ+Pfio7bOy4i97EM2OM42Lu
            fF1WPz/mTRe1sWqKtT8nafB75ThrNJPkE9eSYqoQUFAdq5wX04/5q6NLIEPRmz56
            aFIz+vyQOK8aRPAZ3TAjJ16yWKfzRt/MTl3JuVmSC8RwmsZc8vuPCQCnnU+uEQGi
            fmk4zy5qh//DeIegB5pIO+2vYYfhM22nbopVLjRH0oE0JGFY0VBb+p5VYgqYMntg
            kUyyElp1gEfxjx6Y+wsMef6Q3p8TtX7oEDmliVaM0OQ4biM1GPuWbRFrCRg4NRPS
            XgGlB3QZrHtkt4mGaRBO54CozOxqWF0mnIAlhHdP3j3bDIlAQoD3EvjW0+jOnFgg
            fmQO8B3oQyKPxWrMIVT3sX8zz5FqTW0K+et1xPdKCPANP46y8JZB3vGgxv6fAn8=
            =5zaw
            -----END PGP MESSAGE-----
          fp: 8DB07DFF329D9D90F8FF6813AB4973958C0D3BA2
        - created_at: "2021-05-01T18:27:06Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2GV5ZhTG0UvAQ/8Da0pxA7SEprAGhmKLKuiNH4NfxQbNHevQJz6jqNJawLl
            iU5gtXBTEcW3B3NEibzpduNIsyK85duSQPLZwzpo8ayPrAwImh6Hkx99aATr4NHv
            4759Sf+Rn9MZQGjVZDjlIDMkhagWuMoObTMNrMBZy2R8O//YUnwnMi9O46MhA8V6
            KLvCAE2X/vABDCB6cM41+4m41S4WecGU74fplF+AMHWuToPiQv0d3LubwKtJb8eq
            Kq9Wcmd9BByyQAouTR8t8YUq18etazW8k39bhVlLT4H+3IVlpoYAbfd6OQ3uR0bN
            aUCWpWJDhCaDWIze9ztD1N8zxx1R0Llw2/lyQCOkul8x5/9lkufu9h0iFcAjJFi5
            A83N7xThg+4INlVYXuyIFbG2cJcKR+OXFa/fpFCkpPvwi7UhEgkVEZqERb0fDqqZ
            XOxmD7BSir0DS40j0m/VUGf+ryenHOjBuHFsH2OyP8IOBXatoFw53DxKWjsM27FU
            EQapCvWG2oxUNzWlE0UZsl/PT3xbZeXyrgxYcC7r4xPQmm6dmomUpE/INHao3tVn
            W6IRw8FmBMfO05m/JkFFji4KcXukSqKqBNhBSc/innQcc7HAJx/tED7c/FwjFqiF
            c3YXokITuwAKJUR301ikqZC3m8A/u5nKf6iwj2swu9uEdXvhWPRAu05YoaoBjfzS
            XgFMWRs2IB3lTSc6N71kBSp6LcJVX4HNbS+S6CuFDCPo7fhkrvvW2Kt+EXpzQx6M
            bzbrnf9HYz67/XvSr94O5+Y0UwHp/cb2h7fwLr51kdRrt2YGP7VJNLCDefPlkPc=
            =tUIq
            -----END PGP MESSAGE-----
          fp: 5921B728515558C66010089800F40C060857D1A7
    encrypted_regex: password|username
    version: 3.7.1
