---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kustomize-controller
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
    - flux-system
  selector:
    matchLabels:
      app: kustomize-controller
  podMetricsEndpoints:
  - port: http-prom
