---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: truecommand
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/Ornias1993/k8s-at-home-Charts.git
  ignore: |
    # exclude all
    /*
    # include deploy crds dir
    !/charts/stable/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: truecommand
  namespace: storage
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/stable/truecommand
      version: 1.0.0
      sourceRef:
        kind: GitRepository
        name: truecommand
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ixsystems/truecommand
      tag: 2.0_beta
      pullPolicy: IfNotPresent
    ingress:
      enabled: true
      hosts:
      - host: "truecommand.${SECRET_DOMAIN}"
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "truecommand.${SECRET_DOMAIN}"
    persistence:
      data:
        enabled: true
        storageClass: "${SC_DB}"
        accessMode: ReadWriteOnce
        size: 50Gi
