# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:/rlJBt836qa/Jx+hMfppX4s7Y/Zlz/TXdNcY,iv:Kn8BZ1AdMVPOBGcv6nsKnu+Dk1ObK64lfFhSD46MljU=,tag:crfJHo5MEROL5ZFRxvTBng==,type:str]
    SECRET_ROOT_DOMAIN: ENC[AES256_GCM,data:0Sal3PbLJWugPgGHQWCYt4cPYg==,iv:aDcC0to6drRonHybRaUWj3M49SUSY6sHhuJhG7WePx4=,tag:w8m/hy9ROgp78wzfAceI2g==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:nLV1rLRTSGs49OwS+gSEVJAxGfF4V5lnug==,iv:YIjv/aWnc5onh7PnTz9XjyYaFcFruySe7xIKh2/QUEA=,tag:Etv7p8bG3JyzVq8xtabrtQ==,type:str]
    SECRET_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:Q/JPEAssOysHfjs+VHXCOyzuaJG+CJXdrpdm6uS03XHgeMc02KO7Zg==,iv:eyTn/7mFs3oF93sbKAqNHrBsBjo+kKzi2Ya26RKr0jI=,tag:Jmlam+Br4rRGqI3bU+oJDA==,type:str]
    SECRET_CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:YaNWnRAnRKJZDPK7MIQIE2p2pya2wovaZkXB0Qx8IdA9VX0xQA==,iv:tRAMuUWeO1SyOoDUAM6ms76fEWaf3pjChOQN+JDpTxc=,tag:ZZETjxWJmSjrpqvPCp++rQ==,type:str]
    SECRET_CLOUDFLARE_ZONEID: ENC[AES256_GCM,data:htUCxA4IV7+2GT0/zlEWY+dhY8G3ea4ZCZYp69oQn8w=,iv:1K9to+3MX5EXAsBzx9JHnVamMtO0ZeoUSJhIbzY/yng=,tag:rS44APtVX7ePKaHcuReauw==,type:str]
    SECRET_CLOUDFLARE_RECORDNAME: ENC[AES256_GCM,data:dEk5lw==,iv:CzFqcLIp61kY55+eyMyP7jBNEI6eo1kpFwPAYbIsKDc=,tag:a0cgsctD8z/QqbMZRsjG2Q==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:By6+GMuCcHJ1WuUDZHbcE36S0rSPli7LHy0ngraB,iv:Vvm6DvzSpeqrESNdxFX8mfanztNlqC6vu3HSlbfg36o=,tag:98ZG3wND+w6bci2yMIP65A==,type:str]
    SECRET_TRAEFIK_TOKEN: ENC[AES256_GCM,data:EOUPgYh4W9E9HRoiEjnXUdR5gKX2jwTyk1hzDtCFfCyj1qCR,iv:6xeXdXTsHwrMp6mECrq3c6V7Q2e9khelFZmVbFteRAo=,tag:vgDiYjwd15IaQ8CNRMPmvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-07T21:30:59Z"
    mac: ENC[AES256_GCM,data:ZbAxVpTBws0UKHz9wJMAdDSF2xVpbyaowXDqsRbfbBu8vDvHC6k2qiTMk8wgStGh+REhdNHCphV2ArTcJIL1GHwTwoevH8YLj7FDZqDS3ST9iWo0HmXqbrXCpnhv93mE0MvVcabjaAH5NGV9BdCKTEtoUEwpCb35QLKDOcbk1Fk=,iv:cxJWnYXi5ax1PtMIgIH0xYto+IeYR5fSQFO627XEyW8=,tag:6hif/7D2EMlgzi1DqrZ2vQ==,type:str]
    pgp:
        - created_at: "2021-05-07T21:30:59Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/auLpaX8YHdARAAi4d+c2uMozAglrjMbZtEHTFAXwvi4ncr8WiLd/fObmtr
            R9DzrtKrjIZGuyLq/oo9VFJEFuyncfBA7i8YdlezDwOrcy9GcD+Jq3iyja/0eW2F
            Raw5Fp2qzH1Y/mFPa1Obo5vyBc6bCOI3MZffRadXuSZNfU7fD/AyJeBXc+rGONqV
            og5UOnR5gJI6xQ/41hGm6yhXrxn9PNnvgRWa7kI3qOYsi2UiFveHde53j4FsO3pn
            pnYPnMHGFB3QWRYQewp8qlprAMMQQ7pulJ3iMNciFPd3aKVibAv7mkikjerDVwz3
            wwXYBYs7Myw8EVu0m3JlSEbej6x5efyjvwSoI35piuf8hp/i2t++ZjGNzL/BxJyH
            vE0Nj+DQks//1jaCKqW9xwVenABHG5LRXzsZ98RtX2CMRTwsoSzw0S2HpG1Fnxb0
            vp7EkeCDQZzJlKjIWDT1cOG6VsFNbpgEZna/Ncwfy5UjjVXzKIsmb6Fpv8yRF6R2
            Hf3GusA66f8IKDXjxGYHmt/d9lgxXQY/zBaPNEAPyGtFMY9KKxe5BtMwLENtUb8K
            MwK5JM/2R6yLhVhJkq7FqGtNA5B6v+yTVrcjc0L/Wp+7vfKEqOwpRzxXdNVrKrK6
            JhL9e9pxkywmOsIS0J4GsYAyOtL0+ZkZc1+mHypvwIocYHimEntA+2jRLjl1gbXS
            XgGZWKViInSZDtaCksopiG0P+CLP00upyKnx/+g5eEGaLlQwUEL26U0mNN2CHpC/
            UUVp1xiRlnV0O3b4mKb1U0h9yXOovS2ceiNr+WYtc5ShF21H8cddmu7SE9PlNnM=
            =mN2+
            -----END PGP MESSAGE-----
          fp: 8DB07DFF329D9D90F8FF6813AB4973958C0D3BA2
        - created_at: "2021-05-07T21:30:59Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2GV5ZhTG0UvAQ//W1IK6r8EcaXjOJKqAwiV7Z9U3aNh3AeAaFZjU6CekiaS
            +3h4oMNoo5iYgMAYynL68r7HzAEl1E52kma91RL1u198T+EEeFmkDpZCgieTY8yq
            ESxllGoGMsbGyUwcVkWf0uc05EZuxSUj1hdnCyiRcNd2hzXBMPX6I2CfmaSAfXrG
            aTq+KycJNNedry2hJydj/+PcscNXHRVGKRhmfDIgKyYsQyDP/EpJzQ7x0Ouj5LRR
            /mtnkz/rmzY7cT7RVB2m0bHmJndAV9otHmwtYOXfBxQA/P2p6maOqdQyAJFPQGBp
            8t8IVEOX52EkaVWxKARVh0tMYY9UTeYTfRybsQU238CbBS/CGXR4DKOo8eZtEIgI
            HZ340TRsUxKyDW+YFe/Lot4XyR01bXpSb+GDF3R/MjUlEcJfXw8U/jmSURHdc/cg
            kkFO8p0zftCkju0IwEc+Zi+AIKxFm7qb17fn7JWwQ4EJbt3bb1aN6+dAnod7j99y
            HPjGFj9NWO7xP5bs20xuqh/9klwyuTtICBz7vcYhEaW7Ad3fgpzhi3L0P1ODU7gM
            ipH+JP4u+J5g8oviYlxtZFdBrXzBZ/+pv9vm+J1M3JW1UqgHp8WEAqdchxJmPOeI
            a9tszS3Ei6T5AmOtavRk9Qd9NRzftLAkj7kV2JNKVngLzEu/0D3+DOlF6xfeO1nS
            XgHE2gqX7Nr3QTcRbW8mdosrTxYC6VxgiZ20vNVTRz2TpA0ms3kzCEzfzzRzQG7J
            lbmFI+amtVUnFEIIUJxE5qLf32ifOpepRfowbcp+ItTfU/XZC4tdTNO+HcKSlQQ=
            =VO3z
            -----END PGP MESSAGE-----
          fp: 5921B728515558C66010089800F40C060857D1A7
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
