# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:8KfaiCfUyY9hw/LClhZChdyc0jJTPOrmTLSB,iv:VbjPYAY8+WYrkFOwDRN/DY8QgeellbideaNTYH3TOBo=,tag:875CK3llL9m20Sahfwbsbg==,type:str]
    SECRET_ROOT_DOMAIN: ENC[AES256_GCM,data:CUpzMcdJ5OowFPCdyWccPBjzmA==,iv:gwOtAEUoPj2/EdHulNoPulPcXX9Qtv4uE0TGEwxmjYk=,tag:3XbQem7EluUcSfLQlI/lYQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:6Uj03SOcRT2JpsTZ3fyWIunXa/Ex0WNCBg==,iv:KshE2nxp1u39SQz4XaTTF2PTsUAmtttEIoTF50ACO68=,tag:5yqj24i4350Goi0wRVGRdg==,type:str]
    SECRET_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:G2y+xfWEoU6UIo6u44t3Y64fyXlL+Dmuox6rq2xzKLZFglzrX/o/GQ==,iv:snxKFkTQCd9ycMJ4UoccaaM+HcOJHru45scQR8s6xyY=,tag:8JDyMhR57iLCS9UT/M9HxQ==,type:str]
    SECRET_CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:e/oG0fq2jjFrjZgsA2bIfCCgigCCnNJO4mq1kHTwbBP1NQieJA==,iv:6nbHEXl5YnSGXiJwlveS7AUXfuC5ALxf8iv0LgCOMyE=,tag:Q9GhfmjLGKxHfcCb+5HlXw==,type:str]
    SECRET_CLOUDFLARE_ZONEID: ENC[AES256_GCM,data:wMxdw5U8BfTGR1JE9jemZLeAwsiXXEhZpVJYegga+d0=,iv:9LM4upUYDX/T2dRFHQBPV6gewgm94HF7dfWuRV21sJw=,tag:33GzmDSWAq991vU5O4V41w==,type:str]
    SECRET_CLOUDFLARE_RECORDNAME: ENC[AES256_GCM,data:8tkCqw==,iv:t0n2VRF3e7+yDPFDbTG0r79z+ii86G32j+A4KHhzR7c=,tag:0xFHQL4GdPy5xo9pPXaHCQ==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:kk7VMvSNw7L1+ZHwQU8O3aEqAyT0o6kd2bq2HTrY,iv:N7n3KNue0f+ogDUqGYMoud61AMJRmmPt895aF1JYfRI=,tag:JhtyqL8Qz5ESRIHqFeNw+g==,type:str]
    SECRET_TRAEFIK_TOKEN: ENC[AES256_GCM,data:xc5WEMG5CIVTPdwIW9qcxEQ5tRdq6PXrAyJ2GfDnG9FvDY64,iv:drpP33zQ/n5mppgQYLwF5qEGIuNJyRskKtOYSJ0VXjw=,tag:ncTIjqB2zNBPdPrLfwL8Eg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-07T21:10:30Z"
    mac: ENC[AES256_GCM,data:4icbvrseqy/lXQCeX1/OWNfxQikGUHWIU0UCE3X1FjratdE5BM/ZxHh2q65+DvhWekL83PWvX4kgv3OLUh335Ou7eXHNe0aqVSndNIx0Dp60BhnB+HCIQthcNahO+LfCGglgZ3JjayVJD+3XP7UpPFcng++r48AsOiKiOmRUXAA=,iv:hzHM0n+NvesnkWu70507FTSxEKnmzmEFC0LN6UBmgc0=,tag:y1tS8eC6eHt8ah8nGy6FGA==,type:str]
    pgp:
        - created_at: "2021-05-07T21:10:29Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/auLpaX8YHdARAAwcGvecLy/rVU/n5rfX28vyjWlEJolpiqRFTrxQzW6i6L
            MTv1rCKIjadDwaVHIZf6p6857uPWtP9WsJwBWcPLehTtQmYN0Qe7y/KPgcGi6B3I
            Qha8ESfcBJP7WeD3CjmLd8m5kv1NdWMcVAaZHeJx1KrMAUY22mlED70SNKvOPXoN
            ZRnfJVIUITOz8iDR7RCPoqL1705KV8PNw914iaX4CgK+v0fUd7CU1H/xhNZnPOA3
            RRsAYKhfk/Kf8JcJHmWLs41zHF1dWKh7qcWC/IwH7LfUxOBmxgdNespdcXHs13ig
            TDNLEwjFAAzOOvcKkj1DczbmhvSfSreePk3EPaOLxaSCTcBO8lpUDXwePD7SJmga
            mFBEWvFzFEI8s4TBE7IstOBObdI590QZXHAnfAM06SrXTUNGuIjF+z8rPk1d+MVL
            Egxi/XcrRa5M4R1KRjDagmgCrLrnx15pivmQ96NxV+laQKT2tS6uBhfZEDTFCfuE
            BT5cb11xdB1xtbNVLiZD/XSPpEC6u+D8UWvfE2aewwdM0K6Z0K3sHTEdfkbYFf37
            St31dIPrnQoblyauVfRSe4mso7+c6clpUtBpePzTIlS3SvUmHb1QzyXxO12COMMn
            t5eT+kJcY2aVK+wp2mw6rd+k+UVRx5o97Pe4zcOs4udgisFp9BeIxUiBuBEXR4LS
            XgGS9pXYN0FuWusApFRLrT4BwOh62lEe01ItBSkJlyvOSq4Vlzn3BXI7JWhbOCLH
            iVFkTjgKq7n8r1TyVoG1RHv94II61Et2xTopVU3/djWujMZxi44JPDf9eCAQs2I=
            =DE9i
            -----END PGP MESSAGE-----
          fp: 8DB07DFF329D9D90F8FF6813AB4973958C0D3BA2
        - created_at: "2021-05-07T21:10:29Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2GV5ZhTG0UvARAAqj+DB3PTIyfrIECltywXMaLyKhXrEhSpNQVk5mfeeokh
            lkoDGJ88EQLLzRpThYCX9FGWT0io+CEmJW4LvkFOGUjH/4pPUM4n4sstRq07gtRR
            ACNwl1W5ji1Ys61gEIwEaORvm6A+pXwidmdsGHKt8W5VJF2SxaKNZkU6jFQaasAq
            COAOr+hQ8QzfEaA+bwsLPJJ0/p9ZDEsYQ0u0WwfsLUl9RhMu4masaJwzjWzTHcRP
            0Pavd4dCe4pvtLsNJVa4HWFsAgj2kWfz9JWzNOUSg2yt+5UJcDNmKE0yNP+tjHis
            qQUTYaoe+qFbZmynqFlqRd+qRFU/ZYZ8+lkXr56ExIwU+pnu7wgxcumfLMyYWSfK
            z1p4OH4q6TUjRmWKcSJrgfksbl9+pwhvlAO8FuZPZf3QXgT9HCFXhQsTaoVto6aC
            MfhcnoBB/8mjAJwVgtqZnjHhx4xSvc2bMjjuFVxJk79tk//Tle8uD5IDNijIuaHm
            X1+Ni5iL0BZ0LyhSePK1QDRbNRFQy+jwOU9oUN6cei9vRa3J0qqlHoEZSKFQE3QV
            YJpigMMV5hTJ5nANlES82elBM21RpDcWgZimoc8AuTcUQhGSzi9nmKA9iQaXcPDI
            k/U3TXJkcFqdBLyKLqo0TUTz3ygtCrjHwaG/Q7hdzJ90gb2fTJQGScUIiYW+bI/S
            XgErfGA4vSKzeEu+4QF0AkcPpjR/5iXd8WSPkmsfdzPsOY238DZTQ+sCPd7Obx/r
            4MuVtPWxSmRuLEiiLvSriQhxR8YX1j5QhpeuV9IJCNJPDv693Cnxyp6AHl3hqwE=
            =vQTb
            -----END PGP MESSAGE-----
          fp: 5921B728515558C66010089800F40C060857D1A7
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
