---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:

  # Router Gateway IP
  GATEWAY_IP: "192.168.10.1"
  # Available IP range for Load Balancer services
  METALLB_ARP_RANGE: "192.168.10.200-192.168.10.230"
  LB_TRAEFIK_IP: "192.168.10.200"
  LB_REGISTRY_IP: "192.168.10.201"
  LB_LOKI_IP: "192.168.10.202"

  # storageClass defaults
  SC_DEFAULT: "local-path"
  SC_DB: "local-path"
  SC_MEDIA: "local-path"
  SC_USERDATA: "local-path"
  SC_BACKUPS: "local-path"
