# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:sRrnwTsAKrwv0K+PUUBBKe8XWNIDbMYL+CHg,iv:puYHJ5DWeNlrKVIVkarHfrtBOpnDpY7LpWP74Ru91uk=,tag:jZ+DToHFEPupEbe0uqO+rg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:CvWVtd6XAusNIW7zOQBeHnDMr0trzc9rCg==,iv:uPVAyfOqcdvALJWhlTCwLGEmUq9jXDx3NrV7hQODmjE=,tag:gdOMpj+7rEvgZ4tA+gRHYw==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:bu/aZJMyoq+cDCBq7D5z/bMyaPigjiF1lXBSY4O3,iv:YIuQhxBwBVLkcq4xebQ1ledbo333Yih8SWTFOvc2dFE=,tag:uPDHJt+BY98C0/gvOMqcJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-06T15:40:29Z"
    mac: ENC[AES256_GCM,data:Ic1WxY0dcgBFDsHhp1mxrYIxKpZq9FgmnZtmDzdCZvCGoAgx04wGTcaCU07ht4LGVR4Q2hOBDTShjChC1m9tlCrN3x+0OkvvG67dGMKYPgJGeKOxa8NG0roSkA+icztsjpsffs81oTgUUbyqMOUlcanaQRoYxyOC78JT/OzBREo=,iv:NqLXbRncy1pOsz7bZ0RG7qB0WolXHveeVReLLfe1c2w=,tag:WHdzQLghLCgVzHCNNtFWOA==,type:str]
    pgp:
        - created_at: "2021-05-06T15:40:29Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/auLpaX8YHdAQ/7BmPfznfmrsrOYGaKTVHq9g0099q17BwV21pzOYtcVAbV
            eID1v5USO2KyDD5iLC90XQDmh1zbkN4jUHfaP/Vw6g84VNTEwxV7x/iiLsEXOGzW
            UQ0JoGPZgjUB1mgHG6Z5s8hG4Q4Mt+41Fn4cgtBZNi9v5glxdZHqy2/0mMr+57/P
            h4W4kpLxjGDZhvOY/iqmojypUBj+JPcd2uFykuhXfHTNHCVzw5lz8BlkSLDKZ9d2
            QaWsJBl45lrEmjD756m9JGvt67VYPgi1SE7jt5bsQthpY5yFk94wX4mta9jwGHid
            SulQRyashzQ9QqeAibDOQ0mnLCK3UNvDG/UVtvfF3yutg8Y4bNnaX3l8ZVIWxsKP
            CZTYJVmwiltGFRsYcGEHe1ObUke0QqOZj5HQmegsDS61g5RttaR4kfPvwBkKHqdq
            vlFFvRlCwqPHTZgbDmyStt6L3PS4lY6dmiu5Wma6rKLZA2Kxb7jAp5wtqPLJWK4w
            UrlFXKswVWWzzvKpgDefAYFjBH4blJAYJAmSwr5N6A257NpMESJ9C4b+zyPJvwrx
            vFmKJi1bm4JKTT7c7omd7ArnpQ4PrJKDi0Nhb0ajx458BkRqpQhOgF7czpwZ5EjN
            32YbECYtTAohsJoDeXpkEzAnzP74Z+2atPdmwr5IP9hrdQjI68Cdi3QpXbj5FcHS
            XAE+pUPZ2nd8C+0oqqPfekr0iaaXOuI/FsFNdIpoH3BX7KOAI49YrxktGNjs5E+h
            GacD5LhUIFZ5KoGobidCM9W/YvvMbN2SCTYcdYu6i1SX5rN7Id3SEPraLOCh
            =BXQg
            -----END PGP MESSAGE-----
          fp: 8DB07DFF329D9D90F8FF6813AB4973958C0D3BA2
        - created_at: "2021-05-06T15:40:29Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2GV5ZhTG0UvAQ//ahajwNKxwoE2T4KTvxhgJ/deBHxKA1AdKU2DlyA2B7d5
            chv0MFsy8Ugrh25mqogNVzs802p05U90/fRR+6do1dfOUWNnmIlLRFuO1mpx0gg9
            Iy8eCz341rXYZoFh0j7pgLwssQ/jcqWa6kjF3g3+U/l0ZamzqlEVUY1XTJrfknz3
            NNCCng1zAoonNNzDAPyVNjHo9Er5JjDVZG+UIJXeYRtciTsqcaX9IQlr4xnt8tKM
            dTiCmGE0Dzn4zty2sLb++I73jHsWW/sLU8B/SXBVJ8B3UUFXuhDV5GrOzKwJe1U2
            mSuhozhK5CYL2d4mKeLyXzYtNBOzcuX4CGAe/JN6X34rJMXzIBO/4QdJ5GzYnZJr
            OrpURaV6a9Tk5xJgB3XtVW+RQ9LIyG01mQMMTKG03jogbzEY/c5Zlyz1McBeW/hY
            F1TeqHONDvCym9FmzlnWmUU4LFyv7YrieITb+bMpK8L5H37BW8VGNREsFKFZHA91
            ekiWYT1No2C7yP/AqMNiRbUfPJXTN8D1XuJITHD2awmc1VVu2D17khl3Z6/od+kJ
            Q6eirWv7XiaZh2krjOtgKCLa8Qh5Rhi/2pYuQHnHJ3GmD7bHOA8C4gsqdGgm7K7G
            HKSsYKMthz3f7NaIw8pAEWqYdLBKnb+ZKFJg7nUAjhFUTX2cHs5k8N9ofH1cQlTS
            XAGpiKGiGM6wP0mpQw8h7JVr1OPltXhQ2H6g9x6tjLrf20jS76P76D1OTiUrtUWd
            xYkwOoOl1lw+k6AeyTfNLAG3xZVwRcRomPWymj7eJp3CuV8/cG31kqKqDxQl
            =LTcg
            -----END PGP MESSAGE-----
          fp: 5921B728515558C66010089800F40C060857D1A7
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
