# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:fYjBRNNkdk3hPCZxSTXvdfpYPb6hfunOPKey,iv:Lv5xbCuvCnBJNotVoPgbwwhJJ3HR1oJK0fsZTrmBXvs=,tag:ThOzyv/c+utlapoa5zvlfA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:wOxhBhR9Wj/jYIhy62DaOIWHwvmqo5aKgQ==,iv:63X1tZUacE21tzbJ0Obgh9SDV/8aTl+yzVonGGIeTiE=,tag:btqSjsMKWn9zXSW/6ylEZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-04-28T10:02:54Z"
    mac: ENC[AES256_GCM,data:cbiz5aAB920Q6Tz4fTfYI9RKh4VgYXhHez6qTzBHQUAynGo9Y6dQJ6NnT7f414AkR2Q/xutIZ8AhWR8e19Z/n21xSSZRX6SDj0eJKRtYeQxJoomsGI0PJd+4Udzxiso9QpQy0HSdDuIXa6VLuuzYxyZGvDmSU5FL5EZxpkcUr+g=,iv:Rc0i4mFsW4h5nPQhNeXv51cuideGfMdR/ru4mZGpSTw=,tag:NZHY8H/bUXhzb4ioxXaxLw==,type:str]
    pgp:
        - created_at: "2021-04-28T10:02:53Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/auLpaX8YHdARAAhrnSARJNjP7bj5WIXoIYK9EI3tYu1QRPxE+Zwjd4R5h1
            xXFp2Lk18W8LOvH/U12egdBeS/P5wrVCSHtye3fl7MBFsSumfVZbOSET5+zCzPwH
            pjHeFzbVsx7O3a6Vx3jBHZ9YDe4t6kcmiO0hVXZrKSCK++brw89d8SfdPp57jFyY
            DyHS/UhvVdv0Az3y+VMa4IX0TrSBBiiI0gzvG2ZMKydzpXLVuuwz0va41oi78F1V
            o98KqjkLvjUXO3p+3SNwoPPeWOM8OFL1yXvfAaeyCSLxCcfizm9JlbqPXq5Fy18d
            jgOE5m3HkmrUUpn5cX1Tnoys/Bma5IwE9GXEpfQHpb9QMIhIW9e8nrteHRXUSbcc
            hXcKJnZDEb97c2HwHiNBNGbzgm8uLfUbaUWIHG5KJ89kzOfIIeHXuCe+w8q1OLCz
            mEByWrZpVxdc90/3AnyzIJJQ6LOe/d/6iftjs55LsZt0/epEJmhTyl+bxnOpkKmq
            Rd+YxB5ruSrS+snnaJoMluJWXAmoTgQJkBw14ebhlZRS7IgPx7haxTsdO/Drr5uU
            yVIMeTyAYaB2SOq7lpPzMrZUHsEncPepqIJcL5GKQxVp+asm+CGNKM08xQeBJ7DF
            R6eDgDCg91nYucbw1bjZCLMMT+0OGqORbnHBziL6ubs2tc56jnEy//b4hjPsJHTS
            XgH91ouV/o7h4H3wBb1EIZV62tRt+So7OtrfD2IDamGEBTxuL46VyKPFe4UQs8BB
            +R0M56jWQQ42zNxD2g9GJWNOmNCkBJ/Iiz1OyUvuU8V9smZ0TW1R9DvkthLx54A=
            =qtL1
            -----END PGP MESSAGE-----
          fp: 8DB07DFF329D9D90F8FF6813AB4973958C0D3BA2
        - created_at: "2021-04-28T10:02:53Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2GV5ZhTG0UvAQ//fBmDCV3rzR8GFVrqavpjJ0CMqJKa4hYyPqfh02zwWz1D
            su9h78KoT8lYzMdbr4GMoMo4br94eWPl38+ywgkZnq3dejTLDnDVDm3ek4pY0ncd
            xLTbG9R7dlDUmRBTojl+rG0fUDWKJrKZ7QDZXD9UnU8tTypj2S2q0KXe2aXBUvRY
            M/eMJYqMO76Nti1YX+qiYXhUD377FgywoeBdR9sHYGAb9z7bELBaME1oVXb3V5Ev
            I5jcfAfy1jmdLlhYXv5fRTskXUhEQLxGIg0dDORTAw9qXrwi1rpdASGb2eO5Z2bT
            YBLMuOvoOSN6fVsOR5zEDVWHnZwlg3gWKTfWXsWecBeW5XiPf/28SqbD+ROuPE5i
            qn4CX+QFjPhCQSneObtg0yQeySl8mPDgPYFGwGjmnLGDxgbRoXz8vx2WnawN9T88
            9tRMtP/RZ4B6hOu2xMMPukJkGbNgIUXWBZ3PFUoOobVaC7jSK+Qm8sGMra0YYmsG
            UCAKT4MQkrqVfnC3rWl040zAaeCD001ODHjHPOB44JPE5tWHYY6bXv2X9ZMEgqj7
            kbl3CXoQ9nUYTnNigW4ox2dNdjTyhSsCDoRLUSTMrs31EQgDbw2n3RpenfTnpuoT
            YyW1LiD1bIBSyeFbTzkW1bcd8vymQjSENpJtqv0U64VxDzU23buOjrzT7exlsj/S
            XgGEoqHuakuTyebharwzKsFW9rOPs2sjkJ3Mg9voTRI6x40Ymd0AuoaMSl9xJp9Z
            Tfoz2d+VFC8DyECfN0Xd2wJEBzNFZK9sKiLw678zlYoUmeCcwChRK2LBEYSG1uA=
            =OncV
            -----END PGP MESSAGE-----
          fp: 5921B728515558C66010089800F40C060857D1A7
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
