# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:lb9IfufcBLCt9IrYssKJ1kNrNA==,iv:158Gcz4IAkHghZyvhFCiAY+kZ8AZcnhEQ2RTTgSyOog=,tag:K5R7xiJPnSMTiyS408vS0Q==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:ptckoX5V7a4Xwlm/5OmL+V2hbJq4CompwA==,iv:Az1L511Ed0N+MIPITLSyBdk84LHVvA7LU9qIFuljNIA=,tag:HC6dqkDHSuFcuZCzSFVK1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-04-28T10:32:39Z"
    mac: ENC[AES256_GCM,data:+ss166/0aLMDWZIRYNAAs5HpHo1j4/e11RFtjvAZzfoBYTcXUa0V0b5qVO+Q+Iw37P7QQK6iQFvO4VcJW1unMTSlpXUrbIxVDwGEdNT6rK8Ug1v2lu3jA8yNH3HRt/nzho2gJhXfhN7+lQhLJCbStg3XI+Io8aPmkPYYcNMBhGI=,iv:K8ooOYns78/zdshOuK2SdsE8jE/LpmzHkU+nxWMtboc=,tag:MSTzm5U3kx6W2h8UDFN6fg==,type:str]
    pgp:
        - created_at: "2021-04-28T10:32:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/auLpaX8YHdAQ//ai6HWBtSkPhq5Vp07NrHzpOpjo2qaoYCLG8iURTtpA9B
            cNeARJorZckC7GGENKn9sfEB1EYITMep5zXBvaxKfT+IXojXHWwWAiJabWmNCYqV
            E6j2fyhhK2P+SGeGdXpiVV0DGyqa/u+dy9dfZ1EsB8otOoT6S6kqt+fV3LTp5BqA
            16LZu/s2keSpRD/eEqR1VZJEXbmBLO9l3dMUbQUk98usIFeenTowrsvWsB1Q9lFJ
            Q1oqhGRi0wIWqC22csLD9aDezo8OvN8vHuJkOWofF9sRzHNs9/TQHRSiqxRY21si
            U6jSomAw7KLPx2iwtKyXQlfhsZE/rRUC7gwCh/JBI1o8Xbspp8V2fuss8NGHjhv3
            KgOQR5JNvIglYMB1PBU9YT0ELIJJYI8p8M15utB4yhVyqVdhNaTRO4ssZulD5HxR
            907RG8qLDoZew4o4lcvUI5sno0rRsZUxRj2J0oVPnR9loCwff/u+Dk3wlKHeeFR8
            PoE6vPzUs09HDjE6WVsx/Y1zYIED2oGz2IiEQXS1h282cCzaVEgKPkgCHLpK4a1k
            gixYpuQvS+5741tbRoV9nsY0T8UHi3Bi1M3i8g6AU5668RXQ28LSQiRRXIVkmaaB
            jqq2ZS/bmtpLpG2hnuB27S1i2QGZAlcP9XzL6A/9Ym/DDkZs+ExymnVtBFxYV+3S
            XgFOfeimavOIgmxT4MXF4SyiLDCcmuHL/JDDukimuhR35fk00XYxFctXIU5XRHZE
            SEdu6aoz4fTqnErvii/jPXELfRY+cX/GM5BmqelXg/HKx2tlTKY1n0Nz2TmUwPk=
            =R6Jh
            -----END PGP MESSAGE-----
          fp: 8DB07DFF329D9D90F8FF6813AB4973958C0D3BA2
        - created_at: "2021-04-28T10:32:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2GV5ZhTG0UvAQ/9FPjs4OSlS1G26IQkAc6t9/9BTUgsEosqlSibaBBssoAe
            gsh3RHaE0x6Ik3xRaolQRDdhsrv9ERg2+TQvSsJVnM2V7R0mMdNifiSUJCQH3ROr
            3MK5UwMoJBI+ybVX69GNftTRSeMlma8Agh3Ct1BqHGrPq9bUGDSu0fH9cIOprLDG
            tgXCJ3irsHHfNEPwSoMvMkO7Qs0GBZoahtix5rdPFh5yeZbJawPx7POCjUSJ8QMe
            RG0nobJIiEPCI89l0Qa81PUVsR3iTinHCJRB4Wq5ouhUrEv5iRWNSKu59n2m7Ptx
            rOZDw7kBhfTOR8hrFGvUTP3jyeLjwBkyo7rFxkZqCfu90BCA56AFn7YBYZYZ0Ui7
            loacFheG9B5juXMbycgwQMVUnMfevZF3xv7TlmKFhzxtO1ZhK40bUSw+yktvDGBI
            WA1RWIYWX6JdvlmodiNa0eENOAqNAVbhkV7FcDwq+7PxyE47izHTwHB8GPO9O8Tb
            Zve4EKNPBcP+pRVAmYCTbeW+hAylC3DkPpHZBCyDHtPneoHUb9MWZdips0icZfzz
            MvgPSE7qetCcBKKh5cLU4Zmvf2pn77rWWd2SS/eS+u25LW5qgLium1YBeonOK2yv
            ca2je8i7vKO94i0xUAiuyp9x57rjkqBjf9oBNUH0m/GSQg9/vyZxC/Sl6dX2RTLS
            XgFH5J6fgnJ2jl/QR0kOuiOScTsCCYJw5z4ZAtGblPDYE30xthLFgXfaYVwYe//x
            05xbVvpF4V7LoG2mp7iHs2jgUlwvMjXzbcziI7qPYNefCm7piieGzSUwMGo1+yg=
            =MNJv
            -----END PGP MESSAGE-----
          fp: 5921B728515558C66010089800F40C060857D1A7
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
