apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helm-release.yaml
- tls-store.yaml
- ingreessroute.yaml
- service-monitor.yaml
- internal-dashboard-service.yaml
- prom-rules.yaml
