---

all:
  children:
    # Control Plane group, do not change the 'control-plane' name
    # hosts should match the filenames in 'host_vars'
    master-nodes:
      hosts:
        ProtC1:
        ProtC2:
        ProtC3:
