---

all:
  children:
    # Control Plane group, do not change the 'control-plane' name
    # hosts should match the filenames in 'host_vars'
    master-nodes:
      hosts:
        k8s-master-a:
        k8s-master-b:
        k8s-master-c:
    db-worker-nodes:
      hosts:
        k8s-db-worker-a:
    worker-nodes:
      hosts:
    # Storage group, these are my NAS devices
    # hosts should match the filenames in 'host_vars'
    storage:
      hosts:
