---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kadalu
  namespace: kadalu-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/kadalu/
      version: 0.0.0-0
      sourceRef:
        kind: GitRepository
        name: kadalu-operator
        namespace: flux-system
      interval: 5m
  values:
